// ============================================================================
// FILE: src/types/landing.ts
// PURPOSE: Landing page type definitions (storefront-verified fields only)
//
// [v4 cleanup — 2026-05-15]
//   - Removed `ProductsBlock`, `ProductsSectionConfig`, `ProductsSection`
//   - Removed `products?: ProductsSection` from `TenantLandingConfig`
//   - Rationale: products-on-landing was deprecated in Phase 3 (2026-05-13).
//     `store/[slug]/page.tsx` only gates on `hero.enabled`. Products live
//     at `/products` page only. The `products` branch was persisted in DB
//     but never consumed by any render path.
//
// [BLOCK MIGRATION — 2026-05-13]
//   - Renamed `HeroBlock` → `BlockId`
//   - Accepts both `block${n}` (new) and `hero${n}` (legacy) as union type
//   - Dispatcher (block.tsx) normalizes both to load block{N}.tsx file
//   - BE validator AJV regex updated to accept both formats too
//
// Backward-compat: legacy data in DB (e.g. "hero1") still validates and
// renders correctly. Studio writes new value "block1" on next save.
//
// Note: `hero.title`, `hero.subtitle`, `hero.config.ctaText`, and
// `hero.config.ctaLink` are RETAINED in `HeroSection` / `HeroSectionConfig`
// because the block dispatcher uses them as a fallback chain when the
// tenant-root fields are empty. They have no Studio UI but are still
// rendered if present in legacy data.
// ============================================================================

// ==========================================
// BLOCK ID TYPES
// ==========================================

/**
 * New canonical block ID format. Generated by block-options.ts and written
 * by studio on save. Example: "block1", "block2", ..., "block25".
 */
type NewBlockId = `block${number}`;

/**
 * Legacy block ID format. Pre-2026-05-13 data may still carry this value.
 * Dispatcher normalizes to NewBlockId by extracting the trailing number.
 * Example: "hero1" → loads block1.tsx
 */
type LegacyBlockId = `hero${number}`;

/**
 * Union accepted by config — supports legacy data without forcing migration.
 * BE validator AJV regex: '^(block|hero)[1-9][0-9]*$'
 */
export type BlockId = NewBlockId | LegacyBlockId;

// ==========================================
// SECTION CONFIG INTERFACES
// ==========================================

interface HeroSectionConfig {
  ctaText?: string;
  ctaLink?: string;
}

// ==========================================
// SECTION INTERFACES
// ==========================================

export interface HeroSection {
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  /** Block variant ID. Accepts new `block${n}` or legacy `hero${n}`. */
  block?: BlockId;
  config?: HeroSectionConfig;
}

// ==========================================
// MAIN CONFIG
// ==========================================

export interface TenantLandingConfig {
  enabled: boolean;
  hero?: HeroSection;
}