'use client';

// ==========================================
// SUBDOMAIN SUGGESTIONS (BUILDER)
// File: src/components/marketing/sections/store-builder/subdomain-suggestions.tsx
//
// [PHASE 3 REFACTOR — May 2026]
// Moved from src/components/marketing/store-builder/subdomain-suggestions.tsx
//   → src/components/marketing/sections/store-builder/subdomain-suggestions.tsx
// Behavior preserved verbatim. Only path changed.
//
// ──────────────────────────────────────────────────────────────────
//
// Phase 3 (Interactive Store Builder, May 2026):
//
// Shown only when SubdomainInput surfaces status `taken`. Renders up
// to 4 alternative slug chips generated by generateSlugSuggestions().
// Tapping a chip rewrites the parent's slug state → debounce kicks in
// → status flips back to `checking` → typically `available`.
//
// Hidden when:
//   - Status is anything other than `taken`
//   - Suggestions array is empty (rare — happens when sanitized base
//     becomes too short for any suffix to fit MAX_LENGTH)
// ==========================================

import { useMemo } from 'react';
import { useTranslations } from 'next-intl';
import { generateSlugSuggestions } from '@/lib/utils/slug-suggestions';

interface SubdomainSuggestionsProps {
  /** The slug that was reported as taken */
  takenSlug: string;
  /** Whether to show this component (parent passes status === 'taken') */
  visible: boolean;
  /** Called with the suggestion the user tapped */
  onPick: (suggestion: string) => void;
}

export function SubdomainSuggestions({
  takenSlug,
  visible,
  onPick,
}: SubdomainSuggestionsProps) {
  const t = useTranslations('marketing.storeBuilder.subdomainStep');

  const suggestions = useMemo(
    () => (visible ? generateSlugSuggestions(takenSlug) : []),
    [takenSlug, visible],
  );

  if (!visible || suggestions.length === 0) return null;

  return (
    <div className="mt-3">
      <p className="text-xs text-muted-foreground">{t('suggestionLabel')}</p>
      <div className="mt-1.5 flex flex-wrap gap-1.5">
        {suggestions.map((s) => (
          <button
            key={s}
            type="button"
            onClick={() => onPick(s)}
            className="inline-flex items-center rounded-full border border-input bg-background px-3 py-1 text-xs font-medium text-foreground transition-colors hover:border-primary hover:bg-primary/5 hover:text-primary"
          >
            {s}
          </button>
        ))}
      </div>
    </div>
  );
}
